### PR TITLE
Replace ifeq

### PR DESCRIPTION
**Pull request by ineiti**
Instead of having an ifeq in the dirinfo target, directly depend on the
new AUTH_DIR target.

### CODE REVIEW

**Comment by tharvik** [comment]
I discussed it with @laurent-girod previously. The merged form is reading the env at loadtime and the newer is doing it at runtime. In this case, as `AUTH_DIR` is only used the generate rules and not really as an envvar, it won't change anything.
And the first form is a tiny bit more readable IMO, so, let's keep it.

**Comment by ineiti** [comment]
And the `ifeq DIR_AUTH_PASSWORD` could be moved to the top of the Makefile, no?

Also, the `ifeq AUTH_DIR` makes it impossible to run

```
make certificate dirinfo
```

as it's evaluated at loading and not at runtime. So the above command fails with `Please generate a certificate...`

**Comment by tharvik** [comment]
> And the `ifeq DIR_AUTH_PASSWORD` could be moved to the top of the Makefile, no?

It could, it depends if you want the user to always specify the password when running it or not.

> Also, the `ifeq AUTH_DIR` makes it impossible to run
> 
> ```
> make certificate dirinfo
> ```
> 
> as it's evaluated at loading and not at runtime. So the above command fails with `Please generate a certificate...`

Yep, that's not a really good Makefile, it would be best for `dirinfo` to depend on the files generated by `certificate` (and to explicit the output files of the latter).

**Comment by ineiti** [comment]
> It could, it depends if you want the user to always specify the password when running it or not.

At least for the two usable commands `certificate` and `dirinfo`. But in fact I'm about to add a third one to create the base64 string for `arti-directtory`.

**Comment by ineiti** [comment]
@tharvik this is another proposal:
- keep the `ifeq PASSWORD`
- remove the `ifeq AUTH_DIR` for a dependency on `AUTH_DIR`

I didn't want to replace the `dirinfo` with `DIR_CACHE`, because you might want to renew the node list even if it already exists.

Does that look better?

**Comment by tharvik** [comment]
> Does that look better?

Indeed; watchout for the whitespaces before the `$(error)`, only a tab would work otherwise, it's not part of the rule.

**Review by tharvik — APPROVED** [review]

**Pull request merged**
